//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livedev
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ErpContext : DbContext
    {
        public ErpContext()
            : base("name=ErpContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Utl_Dynamic_Table_Column> Utl_Dynamic_Table_Column { get; set; }
        public virtual DbSet<Utl_Dynamic_Autocode_Property> Utl_Dynamic_Autocode_Property { get; set; }
        public virtual DbSet<Utl_Dynamic_Company> Utl_Dynamic_Company { get; set; }
        public virtual DbSet<Utl_Dynamic_Company_Group> Utl_Dynamic_Company_Group { get; set; }
        public virtual DbSet<Utl_Dynamic_Company_Logo> Utl_Dynamic_Company_Logo { get; set; }
        public virtual DbSet<Utl_Dynamic_Company_Owner> Utl_Dynamic_Company_Owner { get; set; }
        public virtual DbSet<Utl_Dynamic_Company_Project> Utl_Dynamic_Company_Project { get; set; }
        public virtual DbSet<Utl_Dynamic_Database_Module> Utl_Dynamic_Database_Module { get; set; }
        public virtual DbSet<Utl_Dynamic_Database_Module_Type> Utl_Dynamic_Database_Module_Type { get; set; }
        public virtual DbSet<Utl_Dynamic_Dropdown_Property> Utl_Dynamic_Dropdown_Property { get; set; }
        public virtual DbSet<Utl_Dynamic_Filter_Property> Utl_Dynamic_Filter_Property { get; set; }
        public virtual DbSet<Utl_Dynamic_Global_Param> Utl_Dynamic_Global_Param { get; set; }
        public virtual DbSet<Utl_Dynamic_Menu> Utl_Dynamic_Menu { get; set; }
        public virtual DbSet<Utl_Dynamic_Module> Utl_Dynamic_Module { get; set; }
        public virtual DbSet<Utl_Dynamic_Module_Category> Utl_Dynamic_Module_Category { get; set; }
        public virtual DbSet<Utl_Dynamic_Operator> Utl_Dynamic_Operator { get; set; }
        public virtual DbSet<Utl_Dynamic_Sub_Menu> Utl_Dynamic_Sub_Menu { get; set; }
        public virtual DbSet<Utl_Dynamic_Table> Utl_Dynamic_Table { get; set; }
        public virtual DbSet<Utl_Dynamic_Table_Function> Utl_Dynamic_Table_Function { get; set; }
        public virtual DbSet<Utl_Dynamic_Validation_Property> Utl_Dynamic_Validation_Property { get; set; }
    }
}
