//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livedev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utl_Dynamic_Table
    {
        public Nullable<long> TableId { get; set; }
        public Nullable<long> ModuleId { get; set; }
        public Nullable<long> ApplicationId { get; set; }
        public string TableCaption { get; set; }
        public string ModuleTableCaption { get; set; }
        public string TableName { get; set; }
        public Nullable<byte> RefreshType { get; set; }
        public Nullable<long> ParentTableId { get; set; }
        public Nullable<long> ForeignTableId { get; set; }
        public bool IsExternalDataShow { get; set; }
        public string ExternalDataCaption { get; set; }
        public string ExternalDataFilter { get; set; }
        public Nullable<long> ExistingTableId { get; set; }
        public Nullable<int> ModuleWidth { get; set; }
        public Nullable<int> ModuleHeight { get; set; }
        public Nullable<int> FormWidth { get; set; }
        public string PositionExp { get; set; }
        public Nullable<int> RowPosition { get; set; }
        public Nullable<int> ColPosition { get; set; }
        public Nullable<bool> IsReadOnly { get; set; }
        public Nullable<bool> IsWorkFollow { get; set; }
        public Nullable<bool> IsAutoToggle { get; set; }
        public string ProcedureName { get; set; }
        public string ProcedureCaption { get; set; }
        public string ProcedureValidation { get; set; }
        public Nullable<bool> ProcFireOnTrans { get; set; }
        public string ReportProcedureName { get; set; }
        public Nullable<bool> RptProcForWorksheet { get; set; }
        public string ProcFooterView { get; set; }
        public string ProcFooterDml { get; set; }
        public string ReportFileName { get; set; }
        public Nullable<bool> ShowOnReport { get; set; }
        public string SqlStatement { get; set; }
        public string ObjectType { get; set; }
        public string TemplateType { get; set; }
        public Nullable<decimal> SlNo { get; set; }
        public string DeveloperSyncId { get; set; }
        public Nullable<long> Entry_User_Id { get; set; }
        public string Entry_By { get; set; }
        public Nullable<System.DateTime> Entry_Date { get; set; }
        public string Update_By { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string Check_By { get; set; }
        public Nullable<System.DateTime> Check_Date { get; set; }
        public string Approve_By { get; set; }
        public Nullable<System.DateTime> Approve_Date { get; set; }
        public string Delete_By { get; set; }
        public Nullable<System.DateTime> Delete_Date { get; set; }
        public bool Is_Approved { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
        public int Work_Follow_Position { get; set; }
        public System.Guid Row_Id { get; set; }
        public string Cancel_By { get; set; }
        public Nullable<System.DateTime> Cancel_Date { get; set; }
        public bool Is_Cancel { get; set; }
    }
}
