//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livedev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utl_Dynamic_Database_Module
    {
        public int DatabaseId { get; set; }
        public string DatabaseName { get; set; }
        public string ModuleName { get; set; }
        public string ModuleAlis { get; set; }
        public string Dynamic_Page { get; set; }
        public Nullable<int> ModuleType { get; set; }
        public string ImageFile { get; set; }
        public string ServerName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Status { get; set; }
        public bool IsDeleteBtn { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Sl { get; set; }
        public bool Is_Active { get; set; }
        public Nullable<long> Entry_User_Id { get; set; }
        public string Cancel_By { get; set; }
        public Nullable<System.DateTime> Cancel_Date { get; set; }
        public string Delete_By { get; set; }
        public Nullable<System.DateTime> Delete_Date { get; set; }
        public bool Is_Cancel { get; set; }
        public bool Is_Deleted { get; set; }
        public string Approve_By { get; set; }
        public Nullable<System.DateTime> Approve_Date { get; set; }
        public string Check_By { get; set; }
        public Nullable<System.DateTime> Check_Date { get; set; }
        public string Entry_By { get; set; }
        public Nullable<System.DateTime> Entry_Date { get; set; }
        public bool Is_Approved { get; set; }
        public string Update_By { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public int Work_Follow_Position { get; set; }
    }
}
