//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livedev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utl_Dynamic_Table_Column
    {
        public long ColumnId { get; set; }
        public Nullable<long> TableId { get; set; }
        public string ColumnName { get; set; }
        public string SelectColumnName { get; set; }
        public string ColumnDisplayName { get; set; }
        public string ColumnProperty { get; set; }
        public string ControlType { get; set; }
        public string ParentColumn { get; set; }
        public Nullable<long> ForeignKeyName { get; set; }
        public string ForeignColumnName { get; set; }
        public string ForeignDataFilterBy { get; set; }
        public Nullable<int> ColumnWidth { get; set; }
        public Nullable<int> DbColumnWidth { get; set; }
        public int TransPolicyId { get; set; }
        public Nullable<int> GlobalParamId { get; set; }
        public Nullable<int> GlobalParamValue { get; set; }
        public string DefaultValue { get; set; }
        public Nullable<int> FilterBy { get; set; }
        public Nullable<int> User_Privilege { get; set; }
        public Nullable<bool> IsModuleSelect { get; set; }
        public Nullable<bool> IsFvSelect { get; set; }
        public Nullable<bool> IsGvSelect { get; set; }
        public Nullable<bool> IsForeignTable { get; set; }
        public Nullable<bool> IsDefaultFocus { get; set; }
        public bool IsFvUpdate { get; set; }
        public bool IsFvInsert { get; set; }
        public Nullable<bool> IsFvDataFixed { get; set; }
        public Nullable<bool> IsFvForceEdit { get; set; }
        public Nullable<int> DdlDataSource { get; set; }
        public Nullable<long> LovTableId { get; set; }
        public string TableName { get; set; }
        public string ColumnValue { get; set; }
        public string ColumnText { get; set; }
        public string ColumnTextExp { get; set; }
        public string WhereExpression { get; set; }
        public string OrderByExpression { get; set; }
        public string SqlExpression { get; set; }
        public Nullable<byte> LinkType { get; set; }
        public Nullable<int> LinkPageId { get; set; }
        public Nullable<int> LinkTableId { get; set; }
        public string LinkColumnName { get; set; }
        public string LinkUrl { get; set; }
        public bool IsShow { get; set; }
        public Nullable<int> ReportColumn { get; set; }
        public decimal SlNo { get; set; }
        public string DeveloperSyncId { get; set; }
        public Nullable<long> Entry_User_Id { get; set; }
        public string Entry_By { get; set; }
        public Nullable<System.DateTime> Entry_Date { get; set; }
        public string Update_By { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string Check_By { get; set; }
        public Nullable<System.DateTime> Check_Date { get; set; }
        public string Approve_By { get; set; }
        public Nullable<System.DateTime> Approve_Date { get; set; }
        public string Delete_By { get; set; }
        public Nullable<System.DateTime> Delete_Date { get; set; }
        public bool Is_Approved { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
        public int Work_Follow_Position { get; set; }
        public System.Guid Row_Id { get; set; }
        public string Cancel_By { get; set; }
        public Nullable<System.DateTime> Cancel_Date { get; set; }
        public bool Is_Cancel { get; set; }
    }
}
