//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livedev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utl_Dynamic_Company
    {
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<byte> ReturnTypeId { get; set; }
        public Nullable<int> Mushak_Id { get; set; }
        public bool Is_Vat_Inc { get; set; }
        public Nullable<bool> Is_Fifo { get; set; }
        public Nullable<bool> Is_Rebate_Ratio { get; set; }
        public Nullable<bool> Is_Deemed_Sale { get; set; }
        public Nullable<double> AV_Perc { get; set; }
        public Nullable<int> CN_DN_Valid { get; set; }
        public Nullable<int> Eco_Activity_Id { get; set; }
        public Nullable<int> Owner_Type_Id { get; set; }
        public Nullable<int> Comp_Catg_Id { get; set; }
        public Nullable<int> Comp_Type_Id { get; set; }
        public Nullable<bool> Is_Dealer { get; set; }
        public Nullable<int> Return_Period { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAlis { get; set; }
        public string Owner_Name { get; set; }
        public string Address { get; set; }
        public string Location { get; set; }
        public string Contact { get; set; }
        public string Contact_Person { get; set; }
        public string Phone_No { get; set; }
        public string Fax_No { get; set; }
        public string Email_Id { get; set; }
        public string National_Id { get; set; }
        public string Tin_No { get; set; }
        public Nullable<bool> Is_Central_Reg { get; set; }
        public string Vat_No { get; set; }
        public Nullable<long> Thana_Id { get; set; }
        public Nullable<long> Distric_Id { get; set; }
        public string Post_Code { get; set; }
        public string WebSite { get; set; }
        public string LogoPath { get; set; }
        public byte[] LogoImage { get; set; }
        public byte[] GroupLogoImage { get; set; }
        public string SmtpOut { get; set; }
        public string SmtpPort { get; set; }
        public string MailFromUser { get; set; }
        public string MailUserPassword { get; set; }
        public Nullable<int> Delay_Time { get; set; }
        public string Db_Name { get; set; }
        public string Backup_Path { get; set; }
        public Nullable<decimal> OP_VAT { get; set; }
        public Nullable<decimal> OP_SD { get; set; }
        public Nullable<decimal> Adjust_Perc { get; set; }
        public Nullable<decimal> VAT_Adj_Amt { get; set; }
        public Nullable<decimal> SD_Adj_Amt { get; set; }
        public Nullable<decimal> VAT_Bal_Amt { get; set; }
        public Nullable<decimal> SD_Bal_Amt { get; set; }
        public bool Is_Active { get; set; }
        public Nullable<long> Entry_User_Id { get; set; }
        public string Cancel_By { get; set; }
        public Nullable<System.DateTime> Cancel_Date { get; set; }
        public string Delete_By { get; set; }
        public Nullable<System.DateTime> Delete_Date { get; set; }
        public bool Is_Cancel { get; set; }
        public bool Is_Deleted { get; set; }
        public string Approve_By { get; set; }
        public Nullable<System.DateTime> Approve_Date { get; set; }
        public string Check_By { get; set; }
        public Nullable<System.DateTime> Check_Date { get; set; }
        public string Entry_By { get; set; }
        public Nullable<System.DateTime> Entry_Date { get; set; }
        public bool Is_Approved { get; set; }
        public string Update_By { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public int Work_Follow_Position { get; set; }
    }
}
